# Starter pipeline

trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'run'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      azureSubscription: 'Azure subscription 1(6760ddd3-b09d-4a1d-9718-4f23672f9bec)' # Optional

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

